// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmniCare.Modules.Patients.Infrastructure.Persistence;

#nullable disable

namespace OmniCare.Modules.Patients.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PatientsDbContext))]
    [Migration("20260717193732_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("patients")
                .HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("OmniCare.Modules.Patients.Domain.Entities.ClinicalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorPractitionerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClinicalRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClinicalRecordId");

                    b.ToTable("ClinicalEntries", "patients");
                });

            modelBuilder.Entity("OmniCare.Modules.Patients.Domain.Entities.ClinicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OpenedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "Profession")
                        .IsUnique();

                    b.ToTable("ClinicalRecords", "patients");
                });

            modelBuilder.Entity("OmniCare.Modules.Patients.Domain.Entities.Consent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GrantedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Consents", "patients");
                });

            modelBuilder.Entity("OmniCare.Modules.Patients.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalRegistryNumber")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("Niss");

                    b.Property<Guid?>("ReferentPractitionerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RegisteredOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TreatingPhysicianName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NationalRegistryNumber")
                        .IsUnique();

                    b.ToTable("Patients", "patients");
                });

            modelBuilder.Entity("OmniCare.Modules.Patients.Domain.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClinicalRecordId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PrescribedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrescriberName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionsConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionsPrescribed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClinicalRecordId");

                    b.ToTable("Prescriptions", "patients");
                });

            modelBuilder.Entity("OmniCare.Modules.Patients.Domain.Entities.ClinicalEntry", b =>
                {
                    b.HasOne("OmniCare.Modules.Patients.Domain.Entities.ClinicalRecord", null)
                        .WithMany("Entries")
                        .HasForeignKey("ClinicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmniCare.Modules.Patients.Domain.Entities.Consent", b =>
                {
                    b.HasOne("OmniCare.Modules.Patients.Domain.Entities.Patient", null)
                        .WithMany("Consents")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmniCare.Modules.Patients.Domain.Entities.Patient", b =>
                {
                    b.OwnsOne("OmniCare.Modules.Patients.Domain.ValueObjects.ContactDetails", "Contact", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressLine")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Phone")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("TEXT");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients", "patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("OmniCare.Modules.Patients.Domain.ValueObjects.InsurabilityStatus", "Insurability", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly?>("LastCheckedOn")
                                .HasColumnType("TEXT")
                                .HasColumnName("InsurabilityCheckedOn");

                            b1.Property<int>("State")
                                .HasColumnType("INTEGER")
                                .HasColumnName("InsurabilityState");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients", "patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("OmniCare.Modules.Patients.Domain.ValueObjects.MutualityAffiliation", "Mutuality", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("HasPreferentialRate")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("MemberNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MutualityCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients", "patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("OmniCare.Modules.Patients.Domain.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("LastName");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients", "patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Insurability")
                        .IsRequired();

                    b.Navigation("Mutuality");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("OmniCare.Modules.Patients.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("OmniCare.Modules.Patients.Domain.Entities.ClinicalRecord", null)
                        .WithMany("Prescriptions")
                        .HasForeignKey("ClinicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmniCare.Modules.Patients.Domain.Entities.ClinicalRecord", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("OmniCare.Modules.Patients.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Consents");
                });
#pragma warning restore 612, 618
        }
    }
}
