version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      # Un seul PR pour les paquets fortement couplés
      efcore:
        patterns: ["Microsoft.EntityFrameworkCore*"]
      mediarq:
        patterns: ["Mediarq*"]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
