// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmniCare.Modules.Practitioners.Infrastructure.Persistence;

#nullable disable

namespace OmniCare.Modules.Practitioners.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PractitionersDbContext))]
    partial class PractitionersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("practitioners")
                .HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("OmniCare.Modules.Practitioners.Domain.Entities.Cabinet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BceNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("BceNumber");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("RegisteredOn")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BceNumber")
                        .IsUnique();

                    b.ToTable("Cabinets", "practitioners");
                });

            modelBuilder.Entity("OmniCare.Modules.Practitioners.Domain.Entities.Practitioner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CabinetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InamiNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("InamiNumber");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("RegisteredOn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("InamiNumber")
                        .IsUnique();

                    b.ToTable("Practitioners", "practitioners");
                });

            modelBuilder.Entity("OmniCare.Modules.Practitioners.Domain.Entities.Cabinet", b =>
                {
                    b.OwnsOne("OmniCare.Modules.Practitioners.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CabinetId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("City");

                            b1.Property<string>("Line")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressLine");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("PostalCode");

                            b1.HasKey("CabinetId");

                            b1.ToTable("Cabinets", "practitioners");

                            b1.WithOwner()
                                .HasForeignKey("CabinetId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("OmniCare.Modules.Practitioners.Domain.Entities.Practitioner", b =>
                {
                    b.OwnsOne("OmniCare.Modules.Practitioners.Domain.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("PractitionerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("LastName");

                            b1.HasKey("PractitionerId");

                            b1.ToTable("Practitioners", "practitioners");

                            b1.WithOwner()
                                .HasForeignKey("PractitionerId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
