<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Mediarq" />
    <PackageReference Include="Mediarq.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Patients\OmniCare.Modules.Patients.csproj" />
    <ProjectReference Include="..\Modules\Agenda\OmniCare.Modules.Agenda.csproj" />
    <ProjectReference Include="..\Modules\Billing\OmniCare.Modules.Billing.csproj" />
  </ItemGroup>

</Project>
